#pragma once

//
// This file contains all IDs of game assets 
//


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_PARAGOOMBA	20
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_RED_KOOPA	30
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_SQUARE 6
#define OBJECT_TYPE_PIPE 7
#define OBJECT_TYPE_HARD_BRICK 8

#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_QUESTION_BLOCK	51
#define OBJECT_TYPE_COIN_FROM_QUESTION_BLOCK	52
#define OBJECT_TYPE_TRANSFORM_MUSHROOM	53
#define OBJECT_TYPE_TRANSFORM_LEAF	54
#define OBJECT_TYPE_STATIC	99
#define OBJECT_TYPE_WALL 100

#define MAX_RENDER_LAYER 5

#define PI 3.1415926535898f